config/routes.rb
Postit::Application.routes.draw do
  root to: 'posts#index'
  resources :posts, except: [:destroy] do
    member do
      post 'vote'
    end
    resources :comments, only: [:create] do
      post 'vote', on: :member
    end
  end
  resources :categories, only: [:show, :new, :create]
  resources :users, only: [:show, :create, :edit, :update] do
    member do
      get 'posts'
      get 'comments'
    end
  end
  resources :sessions, only: [:create]

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :categorizations
  has_many :posts, through: :categorizations
  validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable

  belongs_to :post
  belongs_to :user

  validates :body, presence: true

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user
  has_many :categorizations
  has_many :categories, through: :categorizations
  has_many :comments

  validates :title, :url, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :username, use: :slugged

  attr_accessible :username, :email, :password, :password_confirmation, :remember_token
  has_many :posts
  has_many :comments

  has_secure_password
  before_save {|user| user.email = email.downcase}
  before_save :create_remember_token
  validates :username, presence: true, length: {maximum: 50}, uniqueness: {case_sensitive: false}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  validates :password, presence: true, length: {minimum: 6}
  validates :password_confirmation, presence: true
  after_validation {self.errors.messages.delete(:password_digest)}

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :users
  belongs_to :voteable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :user_signed_in, except: [:show]

  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
    @category_name = @category.name

    render 'posts/index'
  end

  def new
    @category = Category.new
  end

  def create
    binding.pry
    @category = Category.new(category_params[:category])

    if @category.save
      flash[:success] = 'Category was successfully created.'
      redirect_to @category
    else
      render 'new'
    end
  end

  private
  def category_params
    params.permit(category: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params[:comment])
    @comment.user = current_user

    if @comment.save
      flash[:success] = 'Comment was successfully created.'
      redirect_to @post
    else
      render 'posts/show'
    end
  end

  def vote
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @vote = Vote.create(vote: params[:vote], voteable: @comment, user_id: current_user.id)

    respond_to do |format|
      format.html {
        flash[:notice] = "Your vote was accepted."
        redirect_to :back
      }
      format.js
    end
  end

  private
  def comment_params
    params.permit(comment: [:body])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :user_signed_in, except: [:index, :show]
  before_filter :find_post, only: [:show, :edit, :update, :vote]

  def index
    @posts = Post.all
  end

  def show
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params[:post])
    @post.user = current_user

    if @post.save
      flash[:success] = 'Post was successfully created.'
      redirect_to @post
    else
      render 'new'
    end
  end

  def update
    if @post.update_attributes(post_params[:post])
      flash[:success] = 'Post was successfully updated.'
      redirect_to @post
    else
      render 'edit'
    end
  end

  def vote
    @vote = Vote.create(vote: params[:vote], voteable: @post, user_id: current_user.id)

    respond_to do |format|
      format.html {
        flash[:notice] = "Your vote was accepted."
        redirect_to :back
      }
      format.js
    end
  end

  private
  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.permit(post: [:title, :url, :description, :category_ids => []])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      flash[:success] = "Signed in successfully, welcome to the Postit!"
      redirect_to user
    else
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    sign_out
    flash[:success] = "You have been logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :find_user, only: [:show, :posts, :comments]
  before_filter :user_signed_in, only: [:edit, :update]
  before_filter :correct_user, only: [:edit, :update]

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params[:user])

    if @user.save
      sign_in @user
      flash[:success] = "Signed in successfully, welcome to the Postit!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    if @user.update_attributes(user_params[:user])
      flash[:success] = "Profile successfully updated."
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end

  def posts
    @posts = @user.posts
  end

  def comments
    @comments = @user.comments.order("created_at desc")
  end

  private
  def find_user
    @user = User.find(params[:id])
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_path, notice: 'Permission.' unless current_user?(@user)
  end

  def user_params
    params.permit(user: [:username, :email, :password, :password_confirmation])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Postit"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !!current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def user_signed_in
    redirect_to signin_path, notice: "Please sign in." unless signed_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end

  def menu_class(action, tab)
    "active" if action == tab
  end
end

app/views/categories/new.html.erb
<% provide(:title, 'Category') %>
<h3>Create a new category</h3>
<hr />

<%= simple_form_for @category do |f| %>
  <%= render 'shared/error_messages', target: @category %>
  <%= f.input :name, input_html: {class: "input-xlarge"}, error: false %>
  <div class="form-actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/comments/vote.js.erb
$("#comment_<%= @comment.id %>_votes").html("<%= @comment.total_votes %> votes")

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
        <ul class="nav">
          <li><%= link_to "Postit!", root_path, :class => 'brand' %></li>
          <li><%= link_to 'All Posts', posts_path %></li>
        </ul>
        <!-- Categories -->
        <div class="btn-group nav_item">
          <a href="#" class="btn btn-small dropdown-toggle" data-toggle="dropdown">Categories<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% Category.all.each do |category| %>
              <li><%= link_to category.name, category %></li>
            <% end %>
            <% if signed_in? %>
              <li class="divider"></li>
              <li><%= link_to "<i class='icon-plus'></i> New Category".html_safe, new_category_path %></li>
            <% end %>
          </ul>
        </div>
        <!-- New Post -->
        <% if signed_in? %>
          <div class="btn-group nav_item">
            <%= link_to 'New Post', new_post_path, class: "btn btn-success btn-small" %>
          </div>
        <% end %>
        <!-- Account -->
        <ul class="nav pull-right">
          <% if signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.username %> <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Setting", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to "Sign out", signout_path, method: :delete %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Sign up', signup_path %></li>
            <li><%= link_to 'Sign in', signin_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= [:notice, :success].include?(name) ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= full_title(yield(:title)) %></title>
  <meta name="description" content="">
  <meta name="author" content="">
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <!-- <%= render 'layouts/messages' %> -->
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <%= yield %>
    <footer></footer>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post, defaults: { error: false } do |f| %>
  <%= render 'shared/error_messages', target: @post %>
  <%= f.input :title, input_html: { class: "input-large" } %>
  <%= f.input :url, label: 'URL', input_html: { class: "input-large" }, hint: "Don't forget http://" %>
  <%= f.input :description, input_html: { class: "input-large" } %>
  <%= f.association :categories, as: :check_boxes %>
  <div class="form-actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h4>Editing post</h4>

<%= render 'form' %>

<%= link_to '← Back to all posts', posts_path %>

app/views/posts/index.html.erb
<% provide(:title, @category_name) %>
<% if @category_name.nil? %>
  <p class="lead">All Posts</p>
<% else %>
  <p class="lead">
  <%= link_to 'All Posts', posts_path %> /
  <%= @category_name %>
  </p>
<% end %>
<hr />

<div class="box-gray">
  <div class="posts">
    <% @posts.each do |post| %>
      <div class="post-line">
        <div class="vote">
          <% if signed_in? %>
          <%= link_to "<i class='icon-arrow-up'></i>".html_safe, vote_post_path(post, vote: true), method: :post, remote: true %>
          <% end %>
          <br />
          <span id='<%= "post_#{post.id}_votes" %>'><%= post.total_votes %> votes</span>
          <br />
          <% if signed_in? %>
          <%= link_to "<i class='icon-arrow-down'></i>".html_safe, vote_post_path(post, vote: false), method: :post, remote: true %>
          <% end %>
        </div>
        <div class="pull-left avatar">
          <%= link_to gravatar_for(post.user), user_path(post.user) %>
        </div>
        <div class="right-info">
          <div class="infos">
            <div class="title">
              <%= link_to post.title, post.url, target: '_blank' %>
            </div>
            <div class="description"><%= truncate(post.description, length: 120) %></div>
            <div class="info">
              <% post.categories.each do |category| %>
                <%= link_to category.name, category_path(category), class: "node" %>
              <% end %>
              •
              <%= link_to post.user.username, user_path(post.user) %>
              <%= "published #{time_ago_in_words(post.created_at)} ago" %>
            </div>
            <div class="comment">
              <%= link_to pluralize(post.comments.count, "comment"), post_path(post) %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<h3>Create a new post</h3>
<hr />

<%= render 'form' %>

<%= link_to '← Back to all posts', posts_path %>

app/views/posts/show.html.erb
<% provide(:title, @post.title) %>
<p class="lead">
  <%= link_to @post.title, @post.url, target: "_blank" %>
</p>
<p>
  <% @post.categories.each do |category| %>
    <span class="label">
      <%= link_to category.name, category %>
    </span>
  <% end %>
</p>
<hr />

<% if signed_in? && current_user == @post.user %>
<div class="pull-right"><%= link_to 'Edit', edit_post_path(@post), class: "btn btn-info btn-small" %></div>
<% end %>
<p><%= @post.description %></p>
<hr />

<div id="replies" class="box-gray">
  <div class="total"><%= pluralize(@post.comments.count, "comment") %></div>
  <div class="items">
    <% @post.comments.each do |comment| %>
      <div class="reply">
        <div class="vote">
          <% if signed_in? %>
          <%= link_to "<i class='icon-arrow-up'></i>".html_safe, vote_post_comment_path(@post, comment, vote: true), method: :post, remote: true %>
          <% end %>
          <br />
          <span id="comment_<%= comment.id %>_votes"><%= comment.total_votes %> votes</span>
          <br />
          <% if signed_in? %>
          <%= link_to "<i class='icon-arrow-down'></i>".html_safe, vote_post_comment_path(@post, comment, vote: false), method: :post, remote: true %>
          <% end %>
        </div>
        <div class="pull-left face">
          <%= link_to gravatar_for(comment.user), user_path(comment.user) %>
        </div>
        <div class="infos">
          <div class="info">
            <%= link_to comment.user.username, user_path(comment.user) %>
            <%= "#{time_ago_in_words(comment.created_at)} ago" %>
          </div>
          <div class="body"><%= comment.body %></div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<hr />

<% if signed_in? %>
  <%= simple_form_for @comment, url: post_comments_path(@post, @comment) do |f| %>
    <%= render 'shared/error_messages', target: @comment %>
    <%= f.input :body, label: 'Leave a comment', label_html: {class: 'comment'}, error: false %>
    <div class="form-actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>
<% else %>
  <div id="comment" class="form" style="background-color: #f5f5f5;">
    <div style="padding: 20px;">
      If you want to leave a comment, you'll need to
      <%= link_to 'login', signin_path, class: "btn btn-primary" %> or
      <%= link_to 'register', signup_path, class: "btn btn-danger" %> to do that
    </div>
  </div>
<% end %>

app/views/posts/vote.js.erb
$("#post_<%= @post.id %>_votes").html("<%= @post.total_votes %> votes");

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      <!-- The form containers <%= pluralize(target.errors.count, "error") %>. -->
      Correct the following errors and try again.
    </div>
    <ul>
      <% target.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_menu.html.erb
<div id="menus" class="subnav">
  <ul class="nav nav-tabs">
    <li class="<%= menu_class(controller.action_name,'show') %>">
      <%= link_to "Profile", user_path(@user) %>
    </li>
    <li class="<%= menu_class(controller.action_name, 'posts') %>">
      <%= link_to "Posts (#{@user.posts.count})", posts_user_path(@user) %>
    </li>
    <li class="<%= menu_class(controller.action_name, 'comments') %>">
      <%= link_to "Comments (#{@user.comments.count})", comments_user_path(@user) %>
    </li>
  </ul>
</div>

app/views/users/comments.html.erb
<%= render 'menu' %>

<div id="replies" class="box-gray">
  <ul class="user-comments">
    <% @comments.each do |comment| %>
      <li>
        <div class="title">
          <%= link_to comment.post.title, comment.post.url %>
          <span class="info"><%= "at #{time_ago_in_words(comment.created_at)} ago" %></span>
        </div>
        <div class="body"><p><%= comment.body %></p></div>
      </li>
    <% end %>
  </ul>
</div>

app/views/users/edit.html.erb
<h3>Update your profile</h3>
<hr />

<%= simple_form_for @user, defaults: { input_html: {class: "input-xlarge"}, error: false } do |f| %>
  <%= render 'shared/error_messages', target: @user %>
  <%= f.input :username, label: "Name" %>
  <%= f.input :email, disabled: true %>
  <%= f.input :password, hint: "Be at least 6 characters" %>
  <%= f.input :password_confirmation, label: "Confirmation" %>
  <div class="profile-photo">
    <%= gravatar_for(@user) %>
    <p><strong><%= link_to "Change your avatar at Gravatar.com", "http://gravatar.com/" %>.</strong></p>
  </div>
  <div class="form-actions">
    <%= f.submit "Update profile", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h3>Sign up</h3>
<hr />

<%= simple_form_for @user, defaults: { input_html: {class: "input-xlarge"}, error: false } do |f| %>
  <%= render 'shared/error_messages', target: @user %>
  <%= f.input :username, label: "Name" %>
  <%= f.input :email, placeholder: "user@example.com" %>
  <%= f.input :password, hint: "Be at least 6 characters" %>
  <%= f.input :password_confirmation, label: "Confirmation" %>
  <div class="form-actions">
    <%= f.submit "Create account", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/posts.html.erb
<%= render 'menu' %>

<div class="box-gray">
  <table class="category-posts table">
    <tbody>
      <tr class="head">
        <td class="category">Category</td>
        <td class="title">Title</td>
        <td class="comment">Reply</td>
      </tr>
      <% @posts.each do |post| %>
        <tr class="<%= cycle('list_odd', 'list_even') %>">
          <td>
            <% post.categories.each do |category| %>
              <%= link_to category.name, category_path(category) %>
            <% end %>
          </td>
          <td>
            <%= link_to post.title, post_path(post.url) %>
            <%= "#{time_ago_in_words(post.created_at)} ago" %>
          </td>
          <td class="comment">
            <%= link_to pluralize(post.comments.count, "comment"), post_path(post) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>

<%= render 'menu' %>

<div class="userinfo">
  <div class="pull-left"><%= gravatar_for @user %></div>
  <ul>
    <li class="username"><%= @user.username %></li>
    <li><strong><%= @user.email %></strong></li>
  </ul>
</div>